---
title: '2019-05-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```
```{r}
(invoiceList$訂單時區 == "America/New_York") ->nyLogical
(invoiceList$訂單時區 == "Asia/Taipei") ->tpLogical
invoiceList$nyLogical -> nyLogical
invoiceList$tpLogical -> tpLogical
nyLogical
tpLogical

library(lubridate)
nyDatetime <- ymd_hms(invoiceList$訂單時區之下單時間[nyLogical],tz ="America/New_York")
tpDatetime <- ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei")
invoiceList$UTC時間[nyLogical] <- with_tz(nyDatetime,tz = "UTC")
invoiceList$UTC時間[tpLogical] <- with_tz(tpDatetime,tz ="UTC")
invoiceList
```

```{r}
library(lubridate)
ymd_hms("1973-02-21 12:05:22", tz="America/New_York") -> fromDateTime
with_tz(fromDateTime,tzone="Asia/Taipei") -> toDateTime
toDateTime
```

```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input,tz=fromTzone)
  answer <- with_tz(time1,tzone = toTzone)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```
```{r}
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
yyyymmdd
```
```{r}
date_convert_twYM <- function(twDates){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}
```
```{r}
date_convert_twYM <- function(twdate){
  yyyy<-as.integer(str_extract(twdate,"(?<=(民國))[:digit:]+"))+1911 
  mm<-str_extract(twdate,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))

  return(yyyymmdd)
}

date_convert_twYM("民國108年5月")
```
```{r}
date_convert_twYM <- function(x){
  library(stringr); library(lubridate)
  yyyy <-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911
  mm <-str_extract(x,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  ans <- ymd(yyyymmdd)
  return(ans)
}
```

