---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(stringr)
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course,"經濟學")
```

#str_c(): 多個字串向量的合併
```{r}
month <- c("3","6","9")
day <- c("2","5","8")
char1 <- c("月")
char2 <-c("日")
str_c(month,char1,day,char2)
```
```{r}
pp <- c("^","-","=")
qq <- c("-","-","=")
pp
qq
str_c(pp,qq,sep = "_")
```
```{r}
dates <- c("3-11", "4-5",  "2-7")
dates
str_replace(dates,"-","月")
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
str_c("https://github.com",username,reponame,sep = "/")
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`

a <- str_sub(birthday,1,4)
b <- str_sub(birthday,5,6)
c <- str_sub(birthday,7,8)
str_c("西元",a,"年",b,"月",c,"日")

```

```{r}
year <-c("099/01","099/02","099/03")
a <- str_sub(year,2,3)
b <- str_sub(year,5,6)
c <- as.integer(a)+1911
str_c("西元",c,"年",b,"月")
```

