---
title: "2019-4-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
```
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```
```{r}
成績單[["個經"]]
```
#list裡面物件可以不同
#c裡面物件需一樣 ex:皆為數字
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```
```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```
```{r}
plasticContainer[["greenBox"]][[1]]
```
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][[3]]
```

#[]代表取出greenBox這個盒子 <- 含paper和scissors
#[[]]代表取出greenBox的paper和scissors

```{r}
plasticContainer
extract1 <- plasticContainer[c("greenBox")]
extract2 <- plasticContainer[[c("greenBox")]]
extract1[[1]][[1]]
extract2[1]
```
```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
plasticContainer
```
```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```
$.:
只能用在list vector，且
只能取「一個」元素，其中
.一定為「元素名稱」
```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```

