---
title: '2019-04-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
m2<-matrix(c("a","b","c","d"),2,2)
m2
class(m2)
typeof(m2)
m2[[3]]
m2[c(T,F,F,T)]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
StuList[[2]][3]
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
StuList[[2]][3]
```

```{r}
as.data.frame(StuList)
StuList
```
```{r}
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m)
```
```{r}
chosenLETTERS<-LETTERS[1:16]
matObji<-matrix(chosenLETTERS,4,4)
matObji
```
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
m
```
```{r}
matObji 
matObji[c(3),c(2,4,4,1)]
matObji[c(T,F,F,T),c(F,T,T,T)]
```
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}

```

```{r}

```

```{r}

```

